# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

# Site settings
title: "Blog - Joe Butler"
description:
   The important thing is not to stop questioning.
   Curiosity has its own reason for existing.
   <br>
   <i>Albert Einstein</i>
url: "/"
exclude:
  - vendor

#email:
#blog logo
#logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/collage.jpg"

permalink: /:categories/:title/

name: 'Joe Butler'
author: 'Joe Butler'
author_image: "/assets/images/author.jpg"

timezone: "America/New_York"
paginate:	5

plugins:
  - jekyll-gist

blog_url: "https://joebutler.tech" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: 'vagabond_hacker'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon: linkedin
    url: https://www.linkedin.com/in/joe-butler-coach/
    desc: Joe Butler's Linked In profile
    share_url: 'https://www.linkedin.com/shareArticle'
    share_title: '&amp;title='
    share_link: '?url='
  - icon: twitter
    url: https://twitter.com/vagabond_hacker
    desc: Follow me on twitter
    share_url: 'http://twitter.com/share'
    share_title: "?text="
    share_link: "&amp;url="
  - icon: github
    url: https://github.com/joebutler2
    desc: Fork me on github
    share_url: 
    share_title: 
    share_link: 

sass:
  sass_dir: _sass
